version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    container_name: backend
    env_file:
      - ./backend/.env
    depends_on:
      - nginx
    
  frontend:
    build: 
      context: ./frontend
    container_name: frontend
    depends_on:
      - nginx
      - backend
    
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8080:80"

    