version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    depends_on:
      - nginx
    networks:
      - S3Local

  localstack:
    container_name: "localstack_main"
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    networks:
      - S3Local

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - nginx
      - backend
    networks:
      - S3Local

  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    networks:
      - S3Local
    
networks:
  S3Local:
    driver: bridge
