name: Deploy to GCP Compute Engine

on:
  pull_request:
    branches: [ main-origin ]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to GCP Compute Engine
    runs-on: ubuntu-latest

    steps:
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - name: Setup gcloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Clone Repo
      run: |
        gcloud compute ssh s3ui-instance-group-h0wf --zone=us-east4-c --command="sudo rm -r s3-ui"
        gcloud compute ssh s3ui-instance-group-h0wf --zone=us-east4-c --command="git clone https://github.com/MisterPea/s3-ui.git"

    - name: Stop and Remove Docker Containers
      run: |
        gcloud compute ssh s3ui-instance-group-h0wf --zone=us-east4-c --command="cd s3-ui && sudo docker-compose down"
        gcloud compute ssh s3ui-instance-group-h0wf --zone=us-east4-c --command="sudo docker image prune -a --force"

    - name: Deploy Docker
      run: gcloud compute ssh s3ui-instance-group-h0wf --zone=us-east4-c --command="cd s3-ui && sudo docker-compose up -d"
    
