name: Deploy to GCP Compute Engine

on:
  pull_request:
    branches: [ main-origin ]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to GCP Compute Engine
    runs-on: ubuntu-18.04
    steps:
    - id: 'auth'
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Setup gcloud SDK
      uses: google-github-actions/setup-gcloud@v0
  
    - name: Use gcloud cli
      run: |
        gcloud compute instances list
  
